#include "main.h"
#include "images/garbage.h"
#include "images/nightSky.h"
#include "images/start.h"
#include "images/player.h"
#include "text.h"
#include "images/lose.h"

#include <stdio.h>
#include <stdlib.h>
#include <math.h>

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;
  
  // Load initial application state

  int deltas[] = {-2, -1, 1, 2};
  int ndeltas = sizeof(deltas) / sizeof(deltas[0]);
  int colors[] = { RED, BLUE, GREEN, WHITE, CYAN, YELLOW, MAGENTA };
  int ncolors = sizeof(colors) / sizeof(colors[0]);
  int counter = 0;
  int lcounter = 0;

  struct state cs, ps;
  struct alien *ca, *pa;
  struct player *p, *pp;
  //struct alien aliens[MAX_ALIENS];
  //  struct player player;

  cs.gamestate = START;
  //drawRectDMA(0, 5, 10, 20, WHITE);

  while (1) {

    waitForVBlank();
    
    currentButtons = BUTTONS; // Load the current state of the buttons
    
    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    ps = cs;
    /*for (int i=0; i<NBUTTONS; i++) {
      //buttonJustReleased[i] = KEY_DOWN(i, BUTTONS) == 0 && buttonWasDown[i];
      buttonJustReleased[i] = KEY_JUST_PRESSED(i, BUTTONS, buttonWasDown[i]);
      buttonWasDown[i] = KEY_DOWN(i, BUTTONS) != 0;
    }*/
    
    switch (cs.gamestate) {
      case START:
        //drawFullScreenImageDMA(nightSky);
        //drawImageDMA(10, 20, GARBAGE_WIDTH, GARBAGE_HEIGHT, garbage);
        // state = ?
        
        cs.gamestate = START;
        cs.naliens = MAX_ALIENS;
        cs.score = 0;
        //initialize aliens at the upper half
        for (int i = 0; i < cs.naliens; i++) {
          cs.aliens[i].row = rand() % HEIGHT - 100 ;
          cs.aliens[i].col = rand() % WIDTH-ALIEN_SIZE;
          cs.aliens[i].h = deltas[rand() % ndeltas];
          cs.aliens[i].v = deltas[rand() % ndeltas];
          cs.aliens[i].color = colors[rand() % ncolors];
          cs.aliens[i].size = ALIEN_SIZE;
        }
        //initialise player at the lower half
        p = &cs.player;
        p->col = 120;
        p->row = 120;
        p->height = PLAYER_HEIGHT;
        p->width = PLAYER_WIDTH;
        p->lives = LIVES;

        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          cs.gamestate = PLAY;
          fillScreenDMA(BLACK);
          continue;
        }
        
        drawFullScreenImageDMA(start);
        
        //Why is not visible?
        //drawRectDMA(10, 10, 10, 10, WHITE);
        //drawString(80, 20, "PRESS ENTER TO START", WHITE);
        break;  
      case PLAY:
        counter++;
        lcounter++;
        if (counter == 8000) {
          cs.score++;
        }
        //checking for bounces
        for (int i = 0; i< cs.naliens; i++) {
          ca = &cs.aliens[i];
          ca->row += ca->h;
          ca->col+=ca->v;
          if (ca->row > HEIGHT - ca->size) {
            ca->row= HEIGHT - ca->size;
            ca->h = -ca->h;
          }
          if (ca->col > WIDTH - ca->size) {
            ca->col = WIDTH - ca->size;
            ca->v = -ca->v;
          }
          if (ca->col < 0) {
            ca->col = 0;
            ca->v = -ca->v;
          }
          if (ca->row < 0) {
            ca->row = 0;
            ca->h = -ca->h;
          }
        }
        
        //player functionality
        if (KEY_DOWN(BUTTON_UP, currentButtons)) {
          p->row -= 5;
          if (p->row < 0) {
            p->row = 0; 
          }
        }
        if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {
          p->row += 5;
          if (p->row > HEIGHT-p->height) {
            p->row = HEIGHT - p->height; 
          }
        }
        if (KEY_DOWN(BUTTON_LEFT, currentButtons)) {
          p->col -= 5;
          if (p->col < 0) {
            p->col = 0; 
          }
        }
        if (KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
          p->col += 5;
          if (p->col > WIDTH - p->width) {
            p->col = WIDTH - p->width; 
          }
        }
        //check for contact with aliens
        int con = 0;
        if (lcounter >= 60) {
          for (int i = 0; i< cs.naliens; i++) {
            ca = &cs.aliens[i];
            for (int i = 0; i < ALIEN_SIZE; i++) {
              for (int j = 0; j < ALIEN_SIZE; j++ ) {
                  if (ca->col + j >= p->col && ca->col + j <= p->col+p->width && ca->row + i >= p->row && ca->row + i <= p->row+p->height) {
                    cs.player.lives -= 1;
                    con = 1;
                    lcounter = 0;
                    break;
                    
                  }
              }
              if (con) {
                break;
              }
            }
            if (con) {
              break;
            }      
          }
        }
        //draw player
        pp = &ps.player;
        
        drawRectDMA(pp->row, pp->col, pp->width, pp->height, BLACK);
        drawImageDMA(p->row, p->col, p->width, p->height, player);
        //draw follower
        //drawRectDMA(f->row, f->col, ALIEN_SIZE, ALIEN_SIZE, YELLOW);
        //draw aliens
        for (int i = 0; i < cs.naliens; i++) {
          ca = &cs.aliens[i];
          pa = &ps.aliens[i];
          drawRectDMA(pa->row, pa->col, pa->size, pa->size, BLACK);
          drawRectDMA(ca->row, ca->col, ca->size, ca->size, ca->color);
        }
        char str1[100];
        char sc[100];

        sprintf(sc, "Score: %d", counter/60);
        sprintf(str1, "Lives: %d", cs.player.lives);

        drawRectDMA(145, 5, 255, 10, BLACK);
        drawString(145, 5, sc , WHITE);

        //drawRectDMA(145, 180, 200, 10, BLACK);
        //draw lives
        drawString(145, 180, str1, WHITE);
        
        if (cs.player.lives == 0) {
          cs.gamestate = LOSE;
          delay(100);
          fillScreenDMA(BLACK);
        }
        
        // state = ?
        break;
      case WIN:
        
        // state = ?
        break;
      case LOSE:
          drawImageDMA(0, 0, 240, 140, lose);
          
          drawString(145, 5, sc, WHITE);
          drawString(145, 85, "press ENTER to play again", WHITE);
          if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
            fillScreenDMA(BLACK);
            cs.player.lives = LIVES;
            counter = 0;
            cs.gamestate = PLAY;
          }
        // state = ?
        break;
      

    }
    if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
        fillScreenDMA(BLACK);
        cs.gamestate = START;
      }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

   // You can remove this once previousButtons is used
  UNUSED(ps);
  UNUSED(cs.aliens);
  UNUSED(cs.player); 
  UNUSED(pa); 
  return 0;
}
